name = "FusionSpecies"
uuid = "50b852fb-755b-4f1c-b4e6-649ec8fe8474"
authors = ["Jerome Guterl"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
